// Códigos WMO → descripción e ícono
// Fuente: https://open-meteo.com/en/docs

export const WMO_DESC = {
  0: 'Despejado',
  1: 'Mayormente despejado',
  2: 'Parcialmente nublado',
  3: 'Nublado',
  45: 'Neblina',
  48: 'Escarcha',
  51: 'Llovizna leve',
  53: 'Llovizna',
  55: 'Llovizna fuerte',
  61: 'Lluvia leve',
  63: 'Lluvia',
  65: 'Lluvia fuerte',
  71: 'Nieve leve',
  73: 'Nieve',
  75: 'Nieve fuerte',
  77: 'Granizo',
  80: 'Chubascos',
  81: 'Chubascos fuertes',
  82: 'Chubascos violentos',
  85: 'Nieve moderada',
  86: 'Nieve fuerte',
  95: 'Tormenta',
  96: 'Tormenta con granizo',
  99: 'Tormenta con granizo fuerte',
}

export const WMO_ICON = {
  0: '☀️',
  1: '🌤️',
  2: '⛅',
  3: '☁️',
  45: '🌫️',
  48: '🌫️',
  51: '🌦️',
  53: '🌦️',
  55: '🌧️',
  61: '🌦️',
  63: '🌧️',
  65: '🌧️',
  71: '🌨️',
  73: '❄️',
  75: '❄️',
  77: '🌨️',
  80: '🌧️',
  81: '⛈️',
  82: '⛈️',
  85: '🌨️',
  86: '❄️',
  95: '⛈️',
  96: '⛈️',
  99: '⛈️',
}
